# Generated by Django 5.2.8 on 2025-11-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendentes', '0001_initial'),
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('dataFim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('observacoes', models.TextField(blank=True, max_length=500, verbose_name='Observações')),
                ('atendentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atendentes.atendente')),
                ('chamados', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['id'],
            },
        ),
    ]
