# Generated by Django 5.2.8 on 2025-11-20 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0001_initial'),
        ('clientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=20, verbose_name='Nota')),
                ('comentario', models.TextField(max_length=500, verbose_name='Comentario')),
                ('dataAvaliacao', models.DateField(verbose_name='Data da Avaliacao')),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='atendimentos.atendimento')),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliacoes',
                'ordering': ['id'],
            },
        ),
    ]
