# Generated by Django 5.2.8 on 2025-11-20 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='dataAvaliacao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data da Avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Bom', 'Bom'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Pessimo', 'Pessimo')], max_length=20, verbose_name='Nota'),
        ),
    ]
